version = "2.0"

[[languages]]
name = "TypeScript"
identifiers = ["typescript", "ts"]
comment = { open = "// ~~ " }

[[languages]]
name = "HTML"
identifiers = ["html"]
comment = { open = "<!-- ~~ ", close = " -->" }

[[languages]]
name = "CSS"
identifiers = ["css"]
comment = { open = "/* ~~ ", close = " */" }

[entangled]
watch_list = ["literate/**/*.lit.md"]
