version = "2.0"
watch_list = ["literate.lit.mdx/**/*.lit.md"]
ignore_list = ["node_modules/**", ".venv/**"]

[[languages]]
name = "TypeScript"
identifiers = ["typescript", "ts"]
comment = { open = "// ~~ " }

[[languages]]
name = "HTML"
identifiers = ["html"]
comment = { open = "<!-- ~~ ", close = " -->" }

[[languages]]
name = "CSS"
identifiers = ["css"]
comment = { open = "/* ~~ ", close = " */" }
